/**
 * Migration: 1745625600000_create-sessions-table
 *
 * Purpose: Add user_identity.sessions table for auth-service session lifecycle
 *          (AUTH-002, pre-beta minimal slice — create, find-active, revoke, touch).
 *
 * Schema: user_identity (pre-existing — created by IDP-001 migration 1745539200000)
 * Tables: sessions
 *
 * ADR Compliance:
 * - ADR-001: Schema-per-service isolation — sessions joins the user_identity schema
 *            owned exclusively by auth-service; no cross-schema FK
 * - ADR-003: node-pg-migrate as migration tool standard
 * - ADR-018: Per-service migration tracking — pgmigrations lives inside user_identity schema
 * - ADR-025: Dedicated user_identity schema for identity, sessions, and drafts
 *
 * Decisions locked 2026-04-25 (BL-201 / AUTH-002):
 * - Q-AUTH-002-1: channel CHECK values — same enum as channel_identities.channel
 *     ('whatsapp', 'web', 'rn', 'swift', 'browser_extension')
 * - Q-AUTH-002-2: expires_at has NO default — app (Blake, SESSION_TTL_MS constant)
 *     computes now() + 30d at INSERT time; migration must NOT set a default
 * - Q-AUTH-002-3: partial index WHERE revoked_at IS NULL deferred to IDP-002
 * - Q-AUTH-002-5: last_seen_at updates on channel_identities are NOT part of AUTH-002;
 *     they belong to AUTH-003/004 handlers
 *
 * DR-UC-002: auth-service owns session issuance for all channels.
 *
 * Related RFC: docs/design/RFC-002-sessions-schema.md
 * Related BL item: BL-201
 * Related story: RAILREPAY-AUTH-002
 */

import { MigrationBuilder } from 'node-pg-migrate';

/**
 * UP Migration: Create sessions table, constraints, indexes.
 *
 * Zero-downtime note: auth-service is a freshly deployed skeleton with no session
 * callers in production. The user_identity schema already exists (IDP-001). This
 * migration adds one new table atomically inside a single transaction
 * (run-in-transaction: true in .migrationrc.json). No expand-migrate-contract
 * phasing is required — there is no existing sessions table to alter.
 */
export async function up(pgm: MigrationBuilder): Promise<void> {
  // ─── Step 1: Create sessions table ───────────────────────────────────────
  // DR-UC-002: auth-service owns session issuance for all channels.
  // ADR-025: table lives inside user_identity schema, owned by auth-service.
  pgm.createTable(
    { schema: 'user_identity', name: 'sessions' },
    {
      session_id: {
        type: 'uuid',
        primaryKey: true,
        default: pgm.func('gen_random_uuid()'),
        notNull: true,
        comment: 'Unique session identifier — generated by the database on insert (DR-UC-002)',
      },
      user_id: {
        type: 'uuid',
        notNull: true,
        references: { schema: 'user_identity', name: 'users' },
        referencesConstraintName: 'sessions_user_id_fk',
        onDelete: 'CASCADE',
        comment: 'FK to user_identity.users — CASCADE DELETE removes sessions when user is purged (AC-B1.3)',
      },
      channel: {
        type: 'varchar(32)',
        notNull: true,
        comment: "Channel that originated this session. Allowed values enforced by sessions_channel_check (AC-B1.2, Q-AUTH-002-1, 2026-04-25).",
      },
      issued_at: {
        type: 'timestamptz',
        notNull: true,
        default: pgm.func('NOW()'),
        comment: 'Timestamp when the session was created (immutable after insert)',
      },
      expires_at: {
        type: 'timestamptz',
        notNull: true,
        // INTENTIONALLY NO DEFAULT — Q-AUTH-002-2: application computes now() + 30d
        // at insert time. A migration-level default would allow inserts without an
        // explicit expires_at, masking bugs in the application code (Blake, AUTH-002).
        comment: 'Session expiry — set by app at INSERT to NOW() + SESSION_TTL_MS (no DB default, Q-AUTH-002-2). Refresh via touch() extends this value.',
      },
      revoked_at: {
        type: 'timestamptz',
        notNull: false,
        comment: 'NULL = session is not revoked. Non-null = revocation timestamp set by revoke() (AC-B1.1).',
      },
    }
  );

  // ─── Step 2: channel CHECK constraint ────────────────────────────────────
  // AC-B1.2: channel CHECK allows only the five locked enum values.
  // Constraint name: sessions_channel_check (matches spec exactly).
  // Same enum as channel_identities.channel — locked Q-AUTH-002-1, 2026-04-25.
  pgm.addConstraint(
    { schema: 'user_identity', name: 'sessions' },
    'sessions_channel_check',
    { check: "channel IN ('whatsapp', 'web', 'rn', 'swift', 'browser_extension')" }
  );

  // ─── Step 3: Indexes ─────────────────────────────────────────────────────
  // AC-B1.4: two plain btree indexes (no partial index — deferred to IDP-002 per Q-AUTH-002-3).

  // idx_sessions_user_id: supports "find all sessions for a user" queries.
  // Query pattern: SELECT * FROM user_identity.sessions WHERE user_id = $1
  // Used by: SessionRepository.findActive (filter by user_id + revoked_at + expires_at),
  //          admin session listing, data-retention sweeps by user.
  // Write cost: one entry per session creation — acceptable at pre-beta scale.
  pgm.createIndex(
    { schema: 'user_identity', name: 'sessions' },
    ['user_id'],
    { name: 'idx_sessions_user_id', method: 'btree' }
  );

  // idx_sessions_expires_at: supports future cleanup sweeps.
  // Query pattern: DELETE FROM user_identity.sessions WHERE expires_at < NOW()
  // Deferred cleanup job (post-beta) will use this index to page through expired rows
  // without a full table scan. Pre-creating it now avoids a hot-table ALTER later.
  // Write cost: one entry per session creation — acceptable at pre-beta scale.
  pgm.createIndex(
    { schema: 'user_identity', name: 'sessions' },
    ['expires_at'],
    { name: 'idx_sessions_expires_at', method: 'btree' }
  );

  // ─── Step 4: Table comment ────────────────────────────────────────────────
  pgm.sql(`
    COMMENT ON TABLE user_identity.sessions IS
      'Session records for all channels. Created on OTP verify (AUTH-003), revoked on logout (AUTH-004). 30-day TTL enforced at application level by SessionRepository.touch() — see Q-AUTH-002-2. Owned by auth-service (ADR-025, DR-UC-002).';
  `);
}

/**
 * DOWN Migration: Reverse cleanly.
 *
 * AC-B1.5: drop sessions table with IF EXISTS … CASCADE.
 * Does NOT drop the user_identity schema — that belongs to IDP-001's down().
 * up → down → up must be idempotent.
 *
 * Rollback risk: LOW — auth-service has no session callers in production at this stage
 * (AUTH-003 and AUTH-004 are not yet deployed). The table is created empty.
 * If rolled back during a future live deployment (post AUTH-003), the app must be
 * taken offline first as it would lose session state for authenticated users.
 */
export async function down(pgm: MigrationBuilder): Promise<void> {
  // Drop the sessions table (and its constraints and indexes via CASCADE).
  // IF EXISTS guards against a failed partial UP leaving no table behind.
  // The user_identity schema itself is NOT dropped here — it is owned by
  // IDP-001's migration (1745539200000_create-user-identity-schema.ts).
  pgm.dropTable(
    { schema: 'user_identity', name: 'sessions' },
    { ifExists: true, cascade: true }
  );
}
